# Generated by Django 5.1.3 on 2024-12-03 17:36
# Modified by Alonso on 2024-12-03 17:40

import logging

from django.db import migrations
from django.utils import timezone

logger = logging.getLogger(__name__)


def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    user = get_user_model()

    if not user.objects.filter(username="admin").exists():
        logger.info("Creating new superuser")

        admin = user.objects.create_user(
            "admin",
            password="admin123",
            last_login=timezone.now(),
            # Whatever other attributes you want:
            is_superuser=True,
            is_staff=True,
        )
        admin.save()
    else:
        logger.info("Superuser already created!")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(generate_superuser, migrations.RunPython.noop),
    ]
